create table if not exists kolesa
(
    id               bigint generated by default as identity,
    kolesa_id        bigint,
    kolesa_url       text,
    parsed_at        timestamp,
    brand            text,
    model            text,
    generation       text,
    year             integer,
    city             text,
    body_type        text,
    fuel_type        text,
    engine_volume    numeric,
    mileage          integer,
    transmission     text,
    drive_type       text,
    steering_wheel   text,
    color            text,
    kz_registration  text,
    imgs_count       integer,
    price            integer,
    img_filename     text,
    img_url          text,
    found_img        boolean
);

-- Тестовая таблица с простыми явными ошибками в значениях
create table if not exists kolesa_test_easy_001 (like kolesa including defaults including identity);

-- Тестовая таблица с логическими конфликтами между связанными полями
create table if not exists kolesa_test_logic_001 (like kolesa including defaults including identity);

-- Тестовая таблица со сложными контекстными аномалиями
create table if not exists kolesa_test_hard_001 (like kolesa including defaults including identity);

-- Тестовая таблица со смешанным набором простых, логических и контекстных аномалий
create table if not exists kolesa_test_mixed_001 (like kolesa including defaults including identity);

-- Справочник тестовых датасетов и путей к их CSV/ожидаемым аномалиям
create table if not exists test_datasets
(
    id                      bigint generated by default as identity primary key,
    test_id                 text not null unique,
    table_name              text not null unique,
    difficulty              text not null,
    base_csv_path           text not null,
    csv_path                text not null,
    expected_anomalies_path text not null,
    description             text not null,
    created_at              timestamp default now()
);

-- Ожидаемые аномалии: какие ошибки мы сами внесли и хотим проверить в ответе агента
create table if not exists expected_anomalies
(
    id                 bigint generated by default as identity primary key,
    test_id            text not null references test_datasets(test_id) on delete cascade,
    anomaly_key        text not null,
    table_name         text not null,
    source_row_number  integer,
    kolesa_id          bigint,
    kolesa_url         text,
    anomaly_type       text not null,
    difficulty         text not null,
    changed_columns    text[] not null,
    old_values         jsonb not null,
    new_values         jsonb not null,
    row_selector       jsonb not null default '{}'::jsonb,
    expected_detection text not null,
    description        text not null,
    created_at         timestamp default now(),
    unique (test_id, anomaly_key)
);

-- Снимки профиля таблицы для конкретного прохода анализа
create table if not exists analysis_profiles
(
    id              bigint generated by default as identity primary key,
    test_id         text references test_datasets(test_id),
    table_name      text not null,
    row_count       integer not null,
    schema_snapshot jsonb not null default '{}'::jsonb,
    profile         jsonb not null,
    created_at      timestamp default now()
);

-- История запусков анализа; profile_id связывает запуск с сохраненным профилем
create table if not exists analysis_runs
(
    id              bigint generated by default as identity primary key,
    test_id         text references test_datasets(test_id),
    profile_id      bigint references analysis_profiles(id) on delete set null,
    table_name      text not null,
    agent_name      text not null,
    model_provider  text not null,
    model_name      text not null,
    prompt_version  text,
    started_at      timestamp default now(),
    finished_at     timestamp,
    status          text not null default 'started',
    error_message   text,
    metadata        jsonb not null default '{}'::jsonb
);

alter table if exists analysis_runs
    add column if not exists profile_id bigint references analysis_profiles(id) on delete set null;

-- Найденные агентом аномалии, привязанные к конкретному проходу анализа
create table if not exists agent_findings
(
    id            bigint generated by default as identity primary key,
    run_id        bigint not null references analysis_runs(id) on delete cascade,
    finding_key   text,
    table_name    text not null,
    column_name   text,
    anomaly_type  text not null,
    importance    text,
    row_id        bigint,
    kolesa_id     bigint,
    description   text not null,
    evidence      jsonb not null default '{}'::jsonb,
    raw_finding   jsonb not null default '{}'::jsonb,
    created_at    timestamp default now()
);

-- Итоговые метрики сравнения найденных аномалий с ожидаемыми
create table if not exists evaluation_results
(
    id                    bigint generated by default as identity primary key,
    run_id                bigint not null references analysis_runs(id) on delete cascade,
    test_id               text not null references test_datasets(test_id),
    matcher_name          text not null,
    matcher_model_provider text,
    matcher_model_name    text,
    expected_total        integer not null,
    expected_found        integer not null,
    expected_recall       numeric not null,
    agent_findings_count  integer not null,
    matched_findings_count integer not null,
    missed_count          integer not null,
    extra_findings_count  integer not null,
    report_expected_found integer,
    report_expected_recall numeric,
    report_missed_count   integer,
    raw_matches           jsonb not null default '[]'::jsonb,
    created_at            timestamp default now()
);

alter table if exists evaluation_results
    add column if not exists report_expected_found integer;

alter table if exists evaluation_results
    add column if not exists report_expected_recall numeric;

alter table if exists evaluation_results
    add column if not exists report_missed_count integer;

-- Связи между ожидаемыми аномалиями и findings агента после матчинга
create table if not exists anomaly_detection_matches
(
    id                   bigint generated by default as identity primary key,
    evaluation_result_id bigint not null references evaluation_results(id) on delete cascade,
    expected_anomaly_id  bigint references expected_anomalies(id) on delete cascade,
    agent_finding_id     bigint references agent_findings(id) on delete set null,
    match_status         text not null,
    confidence           numeric,
    matcher_reason       text,
    report_match_status  text,
    report_matcher_reason text,
    created_at           timestamp default now()
);

alter table if exists anomaly_detection_matches
    add column if not exists report_match_status text;

alter table if exists anomaly_detection_matches
    add column if not exists report_matcher_reason text;
