name: anomaly-agent-app

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      LOG_FILE: local/logs/logs.log
    volumes:
      - ./local/logs:/app/local/logs
    networks:
      - anomaly-agent

networks:
  anomaly-agent:
    name: anomaly-agent-net
    external: true
